name: Daily News Discord

on:
  workflow_dispatch:

jobs:
  enviar-noticia:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar requests
        run: pip install requests

      - name: Enviar mensagem para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python daily_news.py
